@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Medical lab technician" as Mlt

participant ":RegisterSampleUI" as UI
participant ":RegisterSampleController" as CTRL
participant "comp\n:Company" as COMP


participant "Barcode" as B

participant "testStore: TestStore" as TSTORE

participant "sample\n:Sample" as SAMPLE
participant "testMap:TestMapper" as TMAPPER

activate Mlt

    Mlt-> UI: start the registration of the sample(s)

    activate UI

        UI -> CTRL : showAvailableTest(sampleDto)

        activate CTRL

            CTRL -> COMP : tStore = getTestStore()
            activate COMP
            deactivate COMP
            CTRL -> TSTORE : ttList=getAvailableTestList()
            activate TSTORE
            deactivate TSTORE
            CTRL -> TMAPPER** : toDTO(tList)
            activate TMAPPER
            ref over TMAPPER
              SD_TestMapper_toDTO_list
            end ref
            TMAPPER --> CTRL : testListDto
            deactivate TMAPPER
            CTRL --> UI : testListDto

        deactivate CTRL

        UI --> Mlt: print the list of tests without registered sample(s)

    deactivate UI

    Mlt -> UI : select test

    activate UI

        UI -> CTRL : printTest(testId)
        activate CTRL
        CTRL -> TSTORE : test = getTestById(testId)
        activate TSTORE
        deactivate TSTORE
        deactivate CTRL

        UI --> Mlt: print select test and ask the number of samples (data,n)

    deactivate UI

    Mlt -> UI : input number of samples(data)

    activate UI
        UI->UI : createSampleList(n)
        loop until number of barcodes is equal to n
        UI -> CTRL : createUPCA(data)
        activate CTRL
        CTRL -> B : createUPCA(data)
        activate B
        B --> CTRL : addToSampleList(UPCA)
        deactivate B
        CTRL --> UI : addToSampleList(UPCA)
        deactivate CTRL
        end

        UI -> CTRL : createSample(sampleList)
        activate CTRL
        CTRL -> SAMPLE : createSample(sampleList)
        activate SAMPLE
        SAMPLE--> CTRL:Sample(sampleList)
        deactivate SAMPLE
        CTRL--> UI:Sample(sampleList)
        deactivate CTRL


        UI --> Mlt: print all data (sampleList) and ask for confirmation

    deactivate UI

Mlt -> UI :  confirms the data

    activate UI
         UI -> CTRL : addSample(sampleList)
         activate CTRL
         CTRL -> TSTORE : addSample(sampleList)
           activate TSTORE
           TSTORE -> TSTORE : validateSample(sampleList)
           TSTORE -> TSTORE : addSample(sampleList)

           TSTORE --> CTRL : Sample added

         deactivate TSTORE

          CTRL --> UI: result
         deactivate CTRL

         UI -> CTRL : setSample(sampleList)
         activate CTRL
         CTRL -> TSTORE : setSample(sampleList)
         activate TSTORE
         deactivate TSTORE

          CTRL --> UI: result
         deactivate CTRL

         UI --> Mlt : informs operation success

    deactivate UI



@enduml