@startuml
'https://plantuml.com/sequence-diagram

participant "store: \n ClientStore" as CS
participant ": \n PasswordGenerator" as PG

activate CS
CS -> CS : pwd = generatePassword()
activate CS
CS -> PG : generatePassword()
activate PG
PG --> CS : pwd
deactivate PG
deactivate CS
@enduml