@startuml
autonumber
'hide footbox
actor "Administrator" as ADMIN

participant ":System" as SYSTEM

ADMIN -> SYSTEM : Create New Parameter Category
activate SYSTEM
SYSTEM --> ADMIN : Requests necessary data (name, code)
deactivate SYSTEM

ADMIN -> SYSTEM : Inserts the data
activate SYSTEM
SYSTEM --> ADMIN : Validates the data and asks for confirmation
deactivate SYSTEM

ADMIN -> SYSTEM : Confirms the data
activate SYSTEM
SYSTEM --> ADMIN : Tell the user that the New parameter category was created
deactivate SYSTEM


@enduml