@startuml

hide methods

class Employee {
    Role clinicalChemistryTechnologist
}

class Test {
    -createdAt
}

class Result {
    -createdAt
    -description
}

Employee"1..*" -- "*"Result : "> write"
Employee"1..*" -up- "*"Test : "> checks"


@enduml