@startuml

hide methods

class Employee {
    - Role clinicalChemistryTechnologist
}

class Test {
    - createdAt
    - DateTime createdAt;
    - String internalCode;
    - String nhsCode;
    - boolean reportDone;
    - boolean resultDone;
    - Report report;
    - Result result;
    - BufferedImage qrcode;
}

class Result {
    -createdAt
    -String result
}

Employee"1..*" -- "*"Result : "> write"
Employee"1..*" -up- "*"Test : "> checks"

@enduml