@startuml

class RecordResultUI {
}

class RecordResultController {
    +getTestWithoutResult()
    +getTestResults(testCode)
    +newResult(text)
    +saveResult()
}

class Company {
    -description
    +getTestStore()
}

class TestStore {
    +getTestWithoutResult()
    +getTestByCode(testCode)
}

class TestListMapper {
    +toDto(lTestNoResult)
}

class Test {
    -createdAt
    -internalCode
    -nhsCode
    +getTestResults()
    +addResult(Result)
    +changeStateToResultDone()
    +generateQRImage(internalCode)
}

class Result {
    -createdAt
    -resultText
    +registerResultDateTime()
}

class DateTime {
    -date
    -time
    +registerCurrentDateTime()
}

RecordResultUI ..> RecordResultController
RecordResultController ..> Company
RecordResultController ..> TestStore
RecordResultController ..> TestListMapper
RecordResultController ..> Test
RecordResultController ..> Result
Company"1" --> "*"Test : "performs"
Company"1" --> "1"TestStore : "uses"
TestStore"1" --> "*"Test : "store"
Test"1" -left-> "1"Result : "originates"
Result ..> DateTime

@enduml