@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Clinical Chemistry Technologist" as CCT
participant ":RecordResultUI" as UI
participant ":RecordResultController" as CTRL
participant ":Company" as COMP
participant ":Test" as T
participant ":Result" as RPRT
participant ":TestParameterResult" as RSLT
participant ":TestStore" as TS
participant ":TestListMapper" as TLM
participant ":DateTime" as DT

CCT -> UI : Record a result for a given test
activate UI
UI -> CTRL :  getListOfTestWithoutResult()
    activate CTRL
        CTRL -> COMP : testStore = getTestStore()
        activate COMP
        deactivate COMP
        CTRL -> TS : getListOfTestWithoutResult()
        activate TS
        deactivate TS
        CTRL -> TLM : lTestNoResultDto = toDto(lTestNoResult)
        activate TLM
        deactivate TLM
    deactivate CTRL
UI --> CCT : asks to select a test \n which doesn't have a result
deactivate UI
CCT -> UI : selects the test
activate UI
UI -> CTRL : getTest(testCode)
    activate CTRL
        CTRL -> TS : selectedTest = getTestByCode(testCode)
        activate TS
        deactivate TS
        CTRL -> T : get(selectedTest)
        activate T
            T -> RSLT : toString()
            activate RSLT
            deactivate RSLT
        deactivate T
    deactivate CTRL
deactivate UI
CCT -> UI : Record the result
activate UI
UI -> CTRL : newResult(description)
    activate CTRL
        CTRL -> RPRT : createResult(description)
        activate RPRT
        deactivate RPRT
    deactivate CTRL
UI --> CCT : validates the result of the test and shows the info \n for user confirmation
deactivate UI
CCT -> UI : confirms the result
activate UI
UI -> CTRL : saveResult()
    activate CTRL
        CTRL -> T : addResult(Result)
        activate T
            T -> T : changeStateToResultDone()
            activate T
                T -> RPRT : registerResultDateTime()
                activate RPRT
                    RPRT -> DT : createdAt = registerCurrentDateTime()
                    activate DT
                    deactivate DT
                deactivate RPRT
            deactivate T
        deactivate T
    deactivate CTRL
UI --> CCT : informs that the Result was saved successfully into the test
deactivate UI

@enduml