@startuml
skinparam classAttributeIconSize 0


class Platform {
  -String designation
  +getTests()
  +getTestByClient(clientId)
}

class RecordResultController {
}

class RecordResultUI {

}

RecordResultUI ..> RecordResultController
RecordResultController ..> Platform


@enduml