@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0



class Test {
  -name
  -VatNumber
  -website
  -phoneNumber
  -email
}

class Employee{
Role ClinicalChemistryTechnologist;
}

class Result {
  -id
  -description
}


Test "1" -- "*" Employee : is delivered to >
Employee "1" -- "*" Result : to make the >



@enduml