@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Clinical Chemistry Technologist" as CCT
participant ":RecordResultUI" as UI
participant ":RecordResultController" as CTRL
participant ":Company" as COMP
participant ":Test" as T
participant ":TestParameterResult" as TPR
participant ":TestStore" as TS
participant ":TestListMapper" as TLM
participant ":DateTime" as DT

CCT -> UI : Record a result for a given test
activate UI
UI -> CTRL :  getListOfTestWithoutResult(labId)
    activate CTRL
        CTRL -> COMP : testStore = getTestStore()
        activate COMP
        deactivate COMP
        CTRL -> TS : getListOfTestWithoutResult(labId)
        activate TS
        deactivate TS
        CTRL -> TLM : lTestNoResultDto = toDto(lTestNoResult)
        activate TLM
        deactivate TLM
    deactivate CTRL
UI --> CCT : asks to select a test \n which doesn't have a result
deactivate UI
CCT -> UI : selects the test
activate UI
UI -> CTRL : getTest(internalCode)
    activate CTRL
        CTRL -> TS : selectedTest = getTestByCode(internalCode)
        activate TS
        deactivate TS
        CTRL -> T : getTestParameters()
        activate T
        deactivate T
    deactivate CTRL
UI --> CCT : presents test parameters
deactivate UI
loop [for each test parameter being analysed]
CCT -> UI : select the test parameter
activate UI
UI --> CCT : asks for value and metric of the result
deactivate UI
CCT -> UI : introduces value and metric
activate UI
UI -> CTRL : addParameterTestResult(parameterCode, value, metric)
    activate CTRL
        CTRL -> T : addParameterTestResult(parameterCode, value, metric)
        activate T
        ref over T
            US12_SD_AddTestResult
        end ref
        deactivate T
    deactivate CTRL
UI --> CCT : inform success

end loop
UI --> CCT : shows all results and asks for confirmation
deactivate UI
CCT -> UI : confirms the results
activate UI
UI -> CTRL : changeStateToResultsDone()
    activate CTRL
        CTRL -> T : changeStateToResultsDone()
        activate T
            T -> T : changeStateToResultDone()
            activate T
                T -> TPR : registerResultDateTime()
                activate TPR
                    TPR -> DT : createdAt = registerCurrentDateTime()
                    activate DT
                    deactivate DT
                deactivate TPR
            deactivate T
        deactivate T
    deactivate CTRL
UI --> CCT : informs that the Result was saved successfully into the test
deactivate UI

@enduml