@startuml
autonumber
'hide footbox
actor "Administrador" as ADMIN

participant ":RegisterNewClinicalAnalysisUI" as UI
participant ":RegisterNewClinicalAnalysis\nRegisterNewClinicalAnalysisController" as CTRL
participant ":Company" as comp
participant "store: ClinicalAnalysisLaboratoryStore " as cals
participant "cal:ClinicalAnalysisLaboratory" as cal

activate ADMIN
ADMIN -> UI : Register a New Clinical Analysis Laboratory
activate UI
UI --> ADMIN : Necessary credentials(laboratoryID, name, address, phoneNumber, tinNumber, typeOfTest)
deactivate UI
ADMIN -> UI : types requested data
activate UI
    UI -> CTRL : registerNewClinicalAnalysisLaboratory(laboratoryID, name, address, phoneNumber, tinNumber, typeOfTest)
    activate CTRL
        CTRL -> comp : store = getClinicalAnalysisLaboratoryStore()
        activate comp
        deactivate comp
        CTRL -> cals : clinicalAnalysisLaboratory= registerClinicalAnalysisLaboratory(laboratoryID, name, address, phoneNumber, tinNumber, typeOfTest)
        activate cals
            cals --> cal** : register(laboratoryID, name, address, phoneNumber, tinNumber, typeOfTest)
        deactivate cals
        CTRL -> cals : validateClinicalAnalysisLaboratory(cal)
        activate cals
        deactivate cals
    deactivate CTRL
    UI --> ADMIN : Validates the data and shows type of test list and ask to select one
deactivate UI
ADMIN -> UI : select requested data(type of test)
activate UI
    UI -> CTRL : saveClinicalAnalysisLaboratory()
    activate CTRL
        CTRL -> cals : saveClinicalAnalysisLaboratory(cal)
        activate cals
            cals -> cals : validateClinicalAnalysisLaboratory(cal)
            activate cals
            deactivate cals
            cals -> cals : addClinicalAnalysisLaboratory(cal)
            activate cals
            deactivate cals
        deactivate cals
    deactivate CTRL
    UI --> ADMIN : informs operation success
deactivate UI

@enduml