@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0


class Company {
  -name
  -location
}

class Administrator {

}

class ClinicalAnalysisLaboratory {
  -laboratoryID
  -name
  -address
  -phoneNumber
  -tinNumber
  -typeOfTestList
}

class TypeOfTest {
  -Designation
}


Company "1" -- "*" Administrator : owns >
Administrator"1..*" -- "*" ClinicalAnalysisLaboratory : Create >
ClinicalAnalysisLaboratory"*" -- "*" TypeOfTest : Has


@enduml