@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0


class Company {
  -Name
  -Location
}

class Administrator {

}

class ClinicalAnalysisLaboratory {
  -LaboratoryID
  -Name
  -Address
  -Phone Number
  -TIN Number
}

class TypeOfTest {
  -Designation
}


Company "1" -- "*" Administrator : owns >
Administrator"1..*" -- "*" ClinicalAnalysisLaboratory : Create >
ClinicalAnalysisLaboratory"*" -- "*" TypeOfTest : Has


@enduml