@startuml
skinparam classAttributeIconSize 0

class NewClinicalAnalysisUI{
}

class NewClinicalAnalysisController
{
    +RegisterNewClinicalAnalysisLaboratory(name, phoneNumber, laboratoryID, tinNumber, address)
    +saveClinicalAnalysisLaboratory()
}

class ClinicalAnalysisLaboratory{
    -name
    -phoneNumber
    -laboratoryID
    -tinNumber
    -address
    + register(clinicalAnalysisLaboratory)
}

class Company{
	-name
	-location
	+getClinicalAnalysisLaboratoryStore()
}

class ClinicalAnalysisLaboratoryStore{
    + validateClinicalAnalysisLaboratory(cal)
    + addClinicalAnalysisLaboratory(cal)
    + registerClinicalAnalysisLaboratory(name, phoneNumber, laboratoryID, tinNumber, address)
    + saveClinicalAnalysisLaboratory(cal)
}

NewClinicalAnalysisUI ..> NewClinicalAnalysisController
NewClinicalAnalysisController .right.> Company
Company"1" --> "1"ClinicalAnalysisLaboratoryStore : uses
ClinicalAnalysisLaboratoryStore"1" -left-> "*"ClinicalAnalysisLaboratory : store

@enduml
