@startuml
skinparam classAttributeIconSize 0

class RegisterEmployeeUI
{
}

class RegisterEmployeeController
{
    +Employee newEmployee(role, name, address, phoneNumber, email, soc)
    +validateEmployee(Employee employee)
}

class Employee
{
	EmployeeID;
	Name;
	Address;
	Phone Number;
	E-Mail;
	Standard Occupational Classification code;
    +validateEmployee(Employee employee)
}

RegisterEmployeeUI ..> RegisterEmployeeController
RegisterEmployeeController ..> Employee
@enduml
