@startuml
autonumber
'hide footbox
actor "Administrator" as ADMIN

participant ":RegisterEmployeeUI" as UI
participant ":RegisterEmployeeController" as CTRL
participant ":Company" as COMP
participant ":EmployeeStore" as EMPS
participant ":Employee" as EMP


ADMIN -> UI : Register a employee
activate UI
    UI --> ADMIN : Requests necessary credentials (organizationRole role,name,\naddress,phoneNumber,email,soc)
deactivate UI

ADMIN -> UI : Inserts the data
activate UI
UI -> CTRL : newEmployee(role,name,\naddress,phoneNumber,email,soc)
    activate CTRL
        CTRL -> COMP : store = getEmployeeStore()
        activate COMP
        deactivate COMP
        CTRL -> EMPS : employee = registerEmployee(oraganizationRole role,name,\naddress,phoneNumber,email,soc)
                activate EMPS
                    EMPS --> EMP** : register(oraganizationRole role,name,\naddress,phoneNumber,email,soc)
                deactivate EMPS
                CTRL -> EMPS : validateEmployee(emp)
                activate EMPS
                deactivate EMPS
    deactivate CTRL
    UI --> ADMIN : Validates the data and asks for confirmation
deactivate UI

ADMIN -> UI : Confirms the data
activate UI

    UI -> CTRL : saveEmployee()

activate CTRL
    CTRL -> COMP : saveEmployee(emp)

activate COMP

    COMP -> COMP : validateEmployee(emp)
    activate COMP
    deactivate COMP
    COMP -> COMP : addEmployee(emp)
    activate COMP
    deactivate COMP
    deactivate COMP


UI --> ADMIN : Saves data and informs success of operation
deactivate COMP
deactivate UI
deactivate CTRL

@enduml
