@startuml
autonumber
'hide footbox
actor "Administrador" as ADMIN

participant ":System" as SYSTEM

ADMIN -> SYSTEM : Ask to register a Employee
activate SYSTEM
SYSTEM --> ADMIN : Requests necessary information (role, name, address, \nphoneNumber, email, soc)

deactivate SYSTEM

ADMIN -> SYSTEM : Inserts the data
activate SYSTEM
SYSTEM --> ADMIN : Validates the data and asks for confirmation
deactivate SYSTEM

ADMIN -> SYSTEM : Confirms the data
activate SYSTEM
SYSTEM --> ADMIN : Tell the user that the Employee has been successfully created
deactivate SYSTEM


@enduml