@startuml
skinparam classAttributeIconSize 0

class CreateParameterCategoryUI{
}

class CreateParameterCategoryController
{
    +createNewParameterCategory(code, nhsId, name, description)
    +saveParameterCategory()
}

class ParameterCategory{
    -code
    -nhsId
    -name
    -description
    +ParameterCategory(code, nhsId, name, description)
}

class Company{
	-designation
	+getParameterCategoryStore()
}

class ParameterCategoryStore{
    +createParameterCategory(code, nhsId, name, description)
    +validateParameterCategory(pc)
    +saveParameterCategory(pc)
    +addParameterCategory()
}

CreateParameterCategoryUI ..> CreateParameterCategoryController
CreateParameterCategoryController .right.> Company
Company --> ParameterCategoryStore : uses
ParameterCategoryStore -left-> ParameterCategory : store

@enduml
