@startuml
skinparam classAttributeIconSize 0

class CreateNewParameterUI{
}

class CreateNewParameterController{
    +CreateNewParameter(shortName, code, nhsId, description, category)
    +saveParameter()
}

class Company{
	-designation
	+getParameterStore()
}

class Parameter{

}

CreateNewParameterController <.up. CreateNewParameterUI
CreateNewParameterController .right.> Company
@enduml
