@startuml
autonumber
'hide footbox
actor "Administrador" as ADMIN

participant ":System" as SYSTEM

ADMIN -> SYSTEM : Create New Parameter
activate SYSTEM
SYSTEM --> ADMIN : Requests necessary data (shortName, description, code, category)
deactivate SYSTEM

ADMIN -> SYSTEM : Inserts the data
activate SYSTEM
SYSTEM --> ADMIN : Validates the data and asks for confirmation
deactivate SYSTEM

ADMIN -> SYSTEM : Confirms the data
activate SYSTEM
SYSTEM --> ADMIN : Tell the user that the Parameter has been created
deactivate SYSTEM


@enduml