@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Lab Coordinator" as LABC

participant ":System" as SYSTEM

LABC -> SYSTEM : validate work done by the clinical chemistry technologist and specialist doctor
activate SYSTEM
SYSTEM --> LABC : shows the test(s) that have the test registration date, the chemical\n analysis date and the diagnosis date registered in the system
deactivate SYSTEM

loop
LABC -> SYSTEM : select the test(s) and validate
activate SYSTEM


SYSTEM --> LABC : ask for validation
deactivate SYSTEM
end
LABC -> SYSTEM : confirms the validation
activate SYSTEM
SYSTEM --> LABC : informs operation success
deactivate SYSTEM


@enduml