@startuml
autonumber
'hide footbox
actor "Receptionist" as RECEP

participant ":CreateClient \n RegisterClientUI" as UI
participant ":CreateClient \n RegisterClientController" as CTRL
participant ":Company" as C
participant "store:ClientStore" as CS
participant "ct: Client" as CL



RECEP -> UI : register a new client
activate UI
    UI --> RECEP : request mandatory data (name, citizen card number, NHS number,\n TIN number, birth date, phone number, email) and optional data (sex)
deactivate UI

RECEP -> UI : inserts the required data
activate UI
    UI -> CTRL : newClient(name, citizenCardNumber, nhsNumber,\n tinNumber, birthDate, sex, phoneNumber, email)

activate CTRL

        CTRL -> C: store =getClientStore()
        activate C
        deactivate C

        CTRL -> CS: client = newClient(name, citizenCardNumber, nhsNumber,\n tinNumber, birthDate, sex, phoneNumber, email)

        activate CS
        CS --> CL** : create(newClient)
        deactivate CS

        CTRL -> CS : validateClient(ct)
        activate CS
        deactivate CS



    deactivate CTRL
    UI --> RECEP : shows the data and asks for confirmation
deactivate UI
RECEP -> UI : confirms the data
activate UI

    UI -> CTRL : saveClient()

activate CTRL
    CTRL -> C : saveClient(ct)

activate C

    C -> C : validateClient(clt)
    activate C
    deactivate C
    C -> C : addClient(clt)
    activate C
    deactivate C
    deactivate C


UI --> RECEP : saves data and informs success of operation
deactivate C
deactivate UI
deactivate CTRL

@enduml
