@startuml
autonumber

participant "parameterMap:ParameterMapper" as PMAPPER
participant "storeParameter: ParameterStore" as PSTORE
participant "listParameterDto : List<ParameterDto>" as PLIST
participant "objDTO: ParameterDto" as PDTO
participant "catStore : CategoryStore" as CATSTORE


[o-> PMAPPER : toDTO(categoryList)
PMAPPER -> PLIST**: create()

loop For each object in categoryList

PMAPPER -> CATSTORE : parameterList = getParametersByCategory(i)
activate CATSTORE
deactivate CATSTORE
    loop For each object in parameterList
        PMAPPER -> PSTORE : parameterObj = getParameterById(j)
        activate PSTORE
        deactivate PSTORE
        PMAPPER -> PMAPPER : objDto = toDTO(parameterObj)
        PMAPPER -> PDTO** : create(code, name)
        PMAPPER -> PLIST : add(objDto)
        activate PLIST
        deactivate PLIST
    end
end

<-- PMAPPER : listParameterDto


@enduml