@startuml
autonumber

participant "parameterMap:ParameterMapper" as PARMAPPER
participant "storeParamater: ParameterStore" as PARSTORE
participant "listParameterDto : List<ParameterDto>" as PARAMETERLIST
participant "objDTO: ParameterDto" as PARAMETERDTO
participant "catStore : CategoryStore" as CATSTORE


[o-> PARMAPPER : toDTO(categoryList)
PARMAPPER -> PARAMETERLIST**: create()

loop For each object in categoryList

PARMAPPER -> CATSTORE : parameterList = getParametersByCategory(i)
activate CATSTORE
deactivate CATSTORE
    loop For each object in parameterList
        PARMAPPER -> PARSTORE : parameterObj = getParameterById(j)
        activate PARSTORE
        deactivate PARSTORE
        PARMAPPER -> PARMAPPER : objDto = toDTO(parameterObj)
        PARMAPPER -> PARAMETERDTO** : create(code, name)
        PARMAPPER -> PARAMETERLIST : add(objDto)
        activate PARAMETERLIST
        deactivate PARAMETERLIST
    end
end

<-- PARMAPPER : listParameterDto


@enduml