@startuml
autonumber

participant "testMap:TestMapper" as TMAPPER
participant "storeTestType: TestTypeStore" as TTSTORE
participant "listTestTypeDto : List<TestTypeDto>" as TESTTLIST
participant "objDTO: TestTypeDto" as TESTTYPEDTO


[o-> TMAPPER : toDTO(testType)
TMAPPER -> TESTTLIST**: create()

loop For each object in testTypeList

TMAPPER -> TTSTORE : testTypeObj = getTestTypeById(i)
activate TTSTORE
deactivate TTSTORE
TMAPPER -> TMAPPER : objDto = toDTO(testTypeObj)
TMAPPER -> TESTTYPEDTO** : create(code)
TMAPPER -> TESTTLIST : add(objDto)
activate TESTTLIST
deactivate TESTTLIST

end

<-- TMAPPER : listTestTypeDto

@enduml