@startuml
autonumber

participant "testMap:TestMapper" as TMAPPER
participant "storeTypeOfTest: TypeOfTestStore" as TTSTORE
participant "listTypeOfTestDto : List<TypeOfTestDto>" as TTLIST
participant "objDTO: TypeOfTestDto" as TTDTO


[o-> TMAPPER : toDTO(TypeOfTest)
TMAPPER -> TTLIST**: create()

loop For each object in typeOfTestList

TMAPPER -> TTSTORE : typeOfTestObj = getTypeOfTestById(i)
activate TTSTORE
deactivate TTSTORE
TMAPPER -> TMAPPER : objDto = toDTO(TypeOfTestObj)
TMAPPER -> TTDTO** : create(code)
TMAPPER -> TTLIST : add(objDto)
activate TTLIST
deactivate TTLIST

end

<-- TMAPPER : listTypeOfTestDto

@enduml