@startuml
autonumber
actor "Receptionist" as RE

activate RE
RE -> ":System" : start the creation of a new test
activate ":System"
":System" --> RE : Asks to select a registered client from the list
deactivate ":System"
RE -> ":System" : Selects one client
activate ":System"
":System" --> RE : shows type of test list
deactivate ":System"
RE -> ":System" : selects a type of test
activate ":System"
":System" --> RE : shows parameter list
loop
deactivate ":System"
RE -> ":System" : selects a parameter
activate ":System"
end
":System" --> RE : shows all data and requests confirmation
deactivate ":System"
RE -> ":System" : confirms the data
activate ":System"
":System" --> RE : informs operation success
deactivate ":System"

deactivate RE

@enduml