@startuml
skinparam classAttributeIconSize 0
left to right direction

class Test {
  -Client client
  -String status
  -List parameterList
  +Test(client, testType, parameterList)
}

class Company {
  -String designation
  + Company(designation)
  + getClientStore()
  + getTypeOfTestStore()
  + getParameterCategoryStore()
  + getParameterStore()
  + getTestStore()
}

class ClientStore {
  + getClientByCitizenCard(citizenCardNumber)
}
class TestTypeStore {
  + getTypeOfTestList()
  + getTypeOfTestById(test)
  + getCategoryListByTypeOfTest(test)
}


class ParameterStore {
  + getParameterById(parameter)
}

class RegisterTestController {
  + List<ParameterDto> getListOfParameter()
  + List<TypeOfTestDto> getTypeOfTestList()
}

class TestStore

class TestTypeMapper {
  + List<TypeOfTestDto> toDTO(List<TypeOfTest> list)
  + TypeOfTestDto toDTO(TypeOfTest obj)
}

class ParameterMapper {
  + List<ParameterDto> toDTO(List<Parameter> list)
  + ParameterDto toDTO(Parameter obj)
}

class ParameterDto {
  - code
  - name
  + ParameterDto(code, name)
}

class TestTypeDto {
  - code
  - description
  +TypeOfTestDto(code, description)
}

class Parameter {
    -code
    -shortName
    -description
    +Parameter(code, shortName, description, category)
}


class RegisterTestUI


RegisterTestController ..> Company
RegisterTestController ..> Test
RegisterTestController ..> ParameterMapper
RegisterTestController ..> TypeOfTestMapper
RegisterTestController ..> TypeOfTestDto
RegisterTestController ..> ParameterDto
TypeOfTestMapper ..> TypeOfTest
TypeOfTestMapper ..> TypeOfTestDto

ParameterMapper ..> Parameter
ParameterMapper ..> ParameterDto

RegisterTestUI ..> ParameterDto
RegisterTestUI ..> TypeOfTestDto
RegisterTestUI ..> RegisterTestController
Company "1" -> "1" TestStore : use
Company "1" --> "1" ClientStore : use
Company "1" --> "1" TypeOfTestStore : use
Company "1" --> "1" ParameterStore : use
TestStore "1" -> "*" Test : knows




@enduml
