@startuml
autonumber
actor "Receptionist" as RE

activate RE
RE -> ":System" : Creation of a new test
activate ":System"
":System" --> RE : Asks to select a registered client from the list
deactivate ":System"
RE -> ":System" : Selects one client
activate ":System"
":System" --> RE : Shows type of test list
deactivate ":System"
RE -> ":System" : Selects a type of test
activate ":System"
":System" --> RE : Shows parameter list

deactivate ":System"
RE -> ":System" : Selects a parameter category
activate ":System"

":System" --> RE : Shows all data and requests confirmation
deactivate ":System"
RE -> ":System" : Confirms the data
activate ":System"
":System" --> RE : Informs operation success
deactivate ":System"

deactivate RE

@enduml