@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Clinical Chemistry Technologist" as CCT
participant ":CheckResultsUI" as UI
participant ":CheckResultsController" as CTRL
participant ":Company" as COMP
participant ":TestStore" as TS
participant ":ClientStore" as CS
participant ":ConfigurationFile" as CF


CCT->UI : check results
activate UI

UI-->CCT: show an option to select the ordering of the clients(TIN or name)
deactivate UI

CCT->UI : selects an option
activate UI
UI-> CTRL : showClients()
activate CTRL
CTRL-> COMP : clientStore = getClientStore()
activate COMP
deactivate COMP
CTRL-> CF : sortedTestList=sortClientList(clientStore)
activate CF
deactivate CF
deactivate CTRL

loop
UI-->CCT:show the Many Labs clients ordered by the\n selected option and ask to select a client

deactivate UI

CCT->UI : selects the client in order to check the historical\n tests performed and tests details/results
activate UI
UI-> CTRL : showTestDetails(tin)
activate CTRL
CTRL->COMP :testStore = getTestStore()
activate COMP
deactivate COMP
CTRL-> CS : client=getClientByTin(tin)
activate CS
deactivate CS
CTRL->TS : getClientTests(client)
activate TS
deactivate TS
deactivate CTRL

UI-->CCT:shows the historical tests performed and tests details/results

deactivate UI
end
@enduml