@startuml
'https://plantuml.com/sequence-diagram

top to bottom direction

Company"1" --- "1..*"Employee : > has
Company"1" -- "*"Client : > has
Company"1" -- "1..*"ClinicalAnalysisLab : > has
LabTechnician"*" -- "1"ClinicalAnalysisLab : > works at
Receptionist"1" -- "*"TestRequest : > register new

Headquarters"1" -- "1"ChemicalLab : > has
Company"1" -left- "1"Headquarters : > owns
Receptionist"1..*" -- "*"Client : > add
Employee <|-- LabTechnician : < is an
Employee <|-- Receptionist : < is an
Employee <|-- LabCoordinator : < is an
Employee <|-- Admin : < is an
Employee <|-- SpecialistDoctor : < is an

Test"1" -- "1"Report : > has
LabTechnician"1" -- "*"Sample : > collect
Sample"1" -- "1"Test : < has
Company"1" -- "1..*"TypeOfTest : > conduct
Company"1" -- "*"Test : > perform
TestRequest"1..*" -- "1""Client" : < does
SpecialistDoctor"1" -- "*"Report : > write
SpecialistDoctor"1..*" -- "1"Headquarters : > works at
Report"1" -- "1"Client : > delivered to
Sample"*" -- "1"ChemicalLab : < owns
LabCoordinator"1" -- "*"Report : > validate

TestRequest"1" -- "1"Test : > originates

TypeOfTest"1" -- "1""Test" : < has

Admin"1..*" -- "*"Category : > create new

Category"1" -- "*"Parameter : < presented under

Test"1" -- "1..*"Parameter : > need to analyse

class Client{
-nhs number
-name
-tin
-birth date
-sex
-phone number
-e-mail
}

class Sample{
-barcode
}

class Report{
-diagnosis
-results
}

class Employee{
-employee ID
-name
-address
-SOC code
-phone number
-e-mail
}

class ClinicalAnalysisLab{
-lab id
-name
-address
-phone number
-tin number
}
class ChemicalLab{
-name
-address
-phone number
-tin number
}

class TestRequest{
-request date
-test type
}

class Company{
-name
-location
}

class Headquarters{
-location
}

class Test{
-date/time of sample collected
-date/time of diagnosis
-date/time of chemical analysis
-date/time of validation
}

class Category{
-nhs id
-internal code
-description
}

class SpecialistDoctor{
-doctor index number
}

@enduml