@startuml
'https://plantuml.com/use-case-diagram

left to right direction
:Receptionist: as Recep
Recep --> (UC1 - Register new Client)
Recep --> (UC2 - Register Test to perform to a client)
:Clinical Chemistry Technologist: --> (UC3 - Record Sample Test Results)
:Specialist Doctor: --> (UC4 - Save diagnosis and report for each sample)
:Specialist Doctor: --> (UC5 - Uses External Module to help Validation Work)
:Specialist Doctor: --> (UC6 - After Validation Work, \n Reports become available in the system)

:Lab Coordinator: as lc
(UC7 - Confirm diagnosis and Reports) as UC7
(UC8 - Send SMS and e-mail to Client) as UC8
:Lab Technician: as lt
(UC9 - Record Sample) as UC9

:Scheduler: --> (UC10 - Generate Daily Reports)
:Scheduler: --> (UC11 - Company Performance Evaluation)
lc --> UC7
lc --> UC8

lt --> UC9

:Admin: --> (UC12 - Add new types of tests to the system)
:Employee: --> (UC14 - Option to order clients by TIF or name)
:Client: --> (US13 - Check his medical tests results)
@enduml