@startuml
'https://plantuml.com/use-case-diagram

left to right direction
:Receptionist: as Recep
Recep --> (UC3 - Register new Client)
Recep --> (UC2 - Register Test to perform to a client)
:Clinical Chemistry Technologist: --> (UC1 - Record Sample Test Results)
:Specialist Doctor: --> (UC4 - Save diagnosis and report for each sample)
:Specialist Doctor: --> (UC5 - Uses External Module to help Validation Work)
:Specialist Doctor: --> (UC6 - After Validation Work, \n Reports become available in the system)

:Lab Coordinator: as lc
(UC12 - Confirm diagnosis and Reports) as UC12

:Lab Technician: as lt
(UC13 - Record Sample) as UC13

:Scheduler: --> (UC15 - Generate Daily Reports)
:Scheduler: --> (UC16 - Company Performance Evaluation)
lc --> UC12


lt --> UC13

:Admin: --> (UC7 - Add new employee to the system)
:Admin: --> (UC8 - Add new clinical analysis labs to the system)
:Admin: --> (UC9 - Add new types of tests to the system)
:Admin: --> (UC10 - Add new parameters to the system)
:Admin: --> (UC11 - Add new parameter category to the system)
:Client: --> (UC14 - Check his medical tests results)
@enduml