@startuml
'https://plantuml.com/sequence-diagram
skinparam classAttributeIconSize 0

class SpecifyANewTypeOfTestUI{
}

class SpecifyANewTypeOfTestController{
    +createNewTypeOfTest(code, description, collectingMethod, pcId)
    +addCategory(pcId)
    +saveTypeOfTest()
}

class Company{
	-designation
	+getTestTypeStore()
	+getParameterCategoryStore()
}

class TypeOfTest{
    -code
    -shortName
    -description
    +TypeOfTest(code, description, collectingMethod, pc)
    +addParameterCategory(pc)
}

class TypeOfTestStore{
    +createTypeOfTest(code, description, collectingMethod, pc)
    +validateTypeOfTest(tot)
    +saveTypeOfTest(tot)
    -addTypeOfTest(tot)
}

class ParameterCategoryStore {
    +getParameterCategoryList()
    +getParameterCategory(pcId)
}

class ParameterCategoryMapper {
    +toDto(lPC)
}



SpecifyANewTypeOfTestController  <.right. SpecifyANewTypeOfTestUI
SpecifyANewTypeOfTestController .right.> Company
Company"1" -up-> "1"TypeOfTestStore : uses
Company"1" --> "1"ParameterCategoryStore : uses
TypeOfTestStore"1" --> "*"TypeOfTest : store
SpecifyANewTypeOfTestController .up.> ParameterCategoryStore
SpecifyANewTypeOfTestController .left.> ParameterCategoryMapper
SpecifyANewTypeOfTestController ..> TypeOfTestStore
SpecifyANewTypeOfTestController ..> TypeOfTest
@enduml

