@startuml
'https://plantuml.com/sequence-diagram

actor Client as CLT
participant ":ClientUI" as UI
participant ":ChangeClientDataController" as CTRL
participant ":Company" as COMP
participant ":ClientStore" as STR
participant ":Email" as EM
participant ":Client" as CL
participant ":UserSession" as US

CLT -> UI : change personal data
activate UI
UI-> CTRL : getClientByEmail()
activate CTRL
CTRL-> COMP : store=getClientStore()
activate COMP
deactivate COMP
CTRL->STR : getClientByEmail()
activate STR
STR -> US : id = getUserId()
activate US
deactivate US

STR->EM: email = getEmail()
activate EM
deactivate EM

deactivate STR


deactivate CTRL



UI--> CLT : shows the registration form with the previous data \n and ask to select the type of data to change


deactivate UI








loop
CLT -> UI : select the type of data that is to validate\n(ex. nhs number, tin number, ect)
activate UI
UI-> CTRL : showData(client)
activate CTRL
deactivate CTRL
UI--> CLT : shows the type of data registered before

deactivate UI

CLT -> UI : writes the changes that he wants
activate UI
UI-> CTRL : setData(client)
activate CTRL
CTRL->STR :setClientData(client)
deactivate CTRL

activate STR
STR->CL : name=setName()
activate CL
deactivate CL
STR->CL : citizenCardNumber=setCitizenCardNumber()
activate CL
deactivate CL
STR->CL : nhsNumber=setNhsNumber()
activate CL
deactivate CL
STR->CL : tinNumber=setTinNumber()
activate CL
deactivate CL
STR->CL : birthDate=setBirthDate()
activate CL
deactivate CL
STR->CL : phoneNumber=setPhoneNumber()
activate CL
deactivate CL
STR->CL : email=setEmail()
activate CL
deactivate CL
deactivate STR
UI--> CLT : shows the date and asks for confirmation
deactivate UI


CLT -> UI : confirms the data
activate UI
UI--> CLT : informs operation success
deactivate UI
end

@enduml