@startuml
'https://plantuml.com/sequence-diagram


Company -- "1"Client :> knows

class Company{
-name
-location
}
class Client{
-name
-citizenCardNumber
-nhsNumber
-tinNumber
-birthDate
-sex
-phoneNumber
-email
}

@enduml