@startuml
autonumber
'hide footbox
actor "Administrator" as ADMIN

participant ":System" as SYSTEM

ADMIN -> SYSTEM : Register a New Clinical Analysis Laboratory
activate SYSTEM
SYSTEM --> ADMIN : request data(name, laboratoryID, address, phoneNumber, tinNumber)
deactivate SYSTEM

ADMIN -> SYSTEM : Types requested data
activate SYSTEM
SYSTEM --> ADMIN : shows test types to be selected
deactivate SYSTEM

SYSTEM -> ADMIN : shows the data and requests a confirmation
activate SYSTEM
ADMIN --> SYSTEM : confirms the data
deactivate SYSTEM
SYSTEM -> ADMIN : Informs operation success

@enduml