@startuml
'https://plantuml.com/sequence-diagram

hide methods
left to right direction
skinparam classAttributeIconSize 0

class Company {
 -designation
}

class Test {
  - nhsCode
  - internalCode
  - createdAT
 }

class Sample{
 -barcodeNumber
}

Company "1" -- "*" Test : performs >
Test "1...*" -- "*" Sample : has >
@enduml