@startuml
'https://plantuml.com/sequence-diagram
autonumber
'hide footbox
actor "Administrador" as ADMIN

participant ":System" as SYSTEM

ADMIN -> SYSTEM : Create New Parameter Category
activate SYSTEM
SYSTEM --> ADMIN : Requests necessary data (code, description, collecting method, Cathegory)
deactivate SYSTEM

ADMIN -> SYSTEM : Inserts the data
activate SYSTEM
SYSTEM --> ADMIN : Validates the data and asks for confirmation
deactivate SYSTEM

ADMIN -> SYSTEM : Confirms the data
activate SYSTEM
SYSTEM --> ADMIN : Tell the user that the new test as been sepecified
deactivate SYSTEM



@enduml