@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Administrator" as ADMIN

participant ":SpecifyANewTypeOfTestUI" as UI
participant ":SpecifyANewTypeOfTestController" as CTRL
participant ":Company" as COMP
participant ":TypeOfTestStore" as TOTS
participant ":TypeOfTest" as TOT
participant ":PCStore" as PCS
participant ":ParameterCategoryMapper" as PCM

ADMIN -> UI : Specify a New Type of test
activate UI
    UI -> CTRL : lPC = getAllParameterCategories()
    activate CTRL
        CTRL -> COMP : pcStore = getParameterCategoryStore()
        CTRL -> PCS : lPC = getAllParameterCategories()
        activate PCS
        deactivate PCS
        CTRL -> PCM : lPCdto = toDto(lPC)
        activate PCM
        deactivate PCM
    deactivate CTRL
    UI --> ADMIN : Requests necessary data (code, description, collecting method)\n and presents parameter categories available to select one
deactivate UI
ADMIN -> UI : Inserts the data and selects one parameter category
activate UI
    UI -> CTRL : specifyANewTypeOfTest(code, description, collecting method, pcId)
    activate CTRL
        CTRL -> COMP : ttStore = getTypeTestStore()
        activate COMP
        deactivate COMP
        CTRL -> PCS : pc = getParameterCategory(pcId)
        activate PCS
        deactivate PCS
        CTRL -> TOTS : tot = createTypeOfTest(code, description, collecting method, pc)
                activate TOTS
                    TOTS --> TOT** : create(code, description, collecting method, pc)
                deactivate TOTS
                CTRL -> TOTS : validateTypeOfTest(tot)
                activate TOTS
                deactivate TOTS
    deactivate CTRL
    UI --> ADMIN : shows all other parameter categories to select another (if needed)
deactivate UI
loop until all categories needed are selected
    ADMIN -> UI : selects another category
    activate UI
        UI -> CTRL : addCategory(pcId)
        activate CTRL
        CTRL -> PCM : pc = getParameterCategory(pcId)
        activate PCM
        deactivate PCM
        CTRL -> TOT : addParameterCategory(pc)
        activate TOT
        deactivate TOT
        CTRL --> UI : confirmation
        deactivate CTRL
        UI --> ADMIN : category added
    deactivate UI
end loop
UI --> ADMIN : shows data and asks confirmation
ADMIN -> UI : Confirms the data
activate UI
    UI -> CTRL : saveTypeOfTest()
    activate CTRL
        CTRL -> TOTS : saveTypeOfTest(tot)
    deactivate CTRL
activate TOTS
            TOTS -> TOTS : validateTypeOfTest(tot)
            activate TOTS
            deactivate TOTS
            TOTS -> TOTS : addTypeOfTest(tot)
            activate TOTS
            deactivate TOTS
        deactivate TOTS
    deactivate CTRL
    UI --> ADMIN : informs operation success
deactivate UI


@enduml