@startuml
'https://plantuml.com/sequence-diagram

autonumber
actor "Administrator" as ADMIN

participant ":SpecifieANewTypeOfTestUI" as UI
participant ":SpecifieANewTypeOfTestController" as CTRL
participant ":Company" as COMP
participant ":TypeOfTestStore" as TOTS
participant ":TypeOfTest" as TOT

ADMIN -> UI : Specifie a New Type of test
activate UI
    UI --> ADMIN : Requests necessary data (code, description, collecting method, cathegory)
deactivate UI
ADMIN -> UI : Inserts the data
activate UI
    UI -> CTRL : SpecifieANewTypeOfTest(code, description, collecting method, cathegory)
    activate CTRL
        CTRL -> COMP : store = getParameterStore()
        activate COMP
        deactivate COMP
        CTRL -> TOTS : tot = createTypeOfTest(code, description, collecting method, cathegory)
                activate TOTS
                    TOTS --> TOT** : create(code, description, collecting method, cathegory)
                deactivate TOTS
                CTRL -> TOTS : validateTypeOfTest(tot)
                activate TOTS
                deactivate TOTS

    deactivate CTRL
    UI --> ADMIN : presents data and asks for confirmation
deactivate UI

ADMIN -> UI : Confirms the data
activate UI
    UI -> CTRL : saveTypeOfTest()
activate TOTS
            TOTS -> TOTS : validateTypeOfTest(tot)
            activate TOTS
            deactivate TOTS
            TOTS -> TOTS : addTypeOfTest(tot)
            activate TOTS
            deactivate TOTS
        deactivate TOTS
    deactivate CTRL
    UI --> ADMIN : informs operation success
deactivate UI


@enduml