@startuml
'https://plantuml.com/sequence-diagram
hide methods
skinparam classAttributeIconSize 0



Company"1" -- "*"TypeOfTest:> conducts
Company"1" -- "*"ParamaterCategory :> adopts
TypeOfTest"*" -- "1"ParamaterCategory :> has a

class TypeOfTest{
-code
-description
-collecting method
}

class Company{
-designation
}

class ParamaterCategory{
    -code
    -name
}
@enduml