@startuml

hide methods

class SpecialistDoctor {
    - doctorIndexNumber
}

class Report {
    -createdAt
    -diagnosis
}

class Result {
    -createdAt
    -value
    -metric
}

SpecialistDoctor"1..*" -- "*"Report : "> write"
SpecialistDoctor"1..*" -up- "*"Result : "> checks"


@enduml