@startuml

class WriteReportUI {
}

class WriteReportController {
    +getTestWithoutReport()
    +getTestResults(testCode)
    +newReport(text)
    +saveReport()
}

class Company {
    -description
    +getTestStore()
}

class TestStore {
    +getTestWithoutReport()
    +getTestByCode(testCode)
}

class TestListMapper {
    +toDto(lTestNoReport)
}

class Test {
    -createdAt
    -internalCode
    -nhsCode
    +getTestResults()
    +addReport(report)
    -changeStateToReportDone()
}

class TestParameterResult {
    -createdAt
    -value
    -metric
    +toString()
}

class Report {
    -createdAt
    -reportText
}

WriteReportUI .right.> WriteReportController
WriteReportController ..> Company
WriteReportController ..> TestStore
WriteReportController .right.> TestListMapper
WriteReportController ..> Test
WriteReportController ..> Report
Company"1" --> "*"Test : "performs"
Company"1" --> "1"TestStore : "uses"
TestStore"1" --> "*"Test : "store"
Test"1" -left-> "1"Report : "originates"
Test"1" -right-> "*"TestParameterResult : "analyses parameter to get"

@enduml
