@startuml
'https://plantuml.com/sequence-diagram

Company -- Employee :> has
Employee <|-- Administrador
Administrador --  TypeOfTest:> specify new

class TypeOfTest{
-code
-description
-collecting method
-Cathegory
}

class Administrador{
  -name
  -function
  -phone
  -email
}

class Employee{
-employeeID
-name
-address
-socCode
-phoneNumber
-email
}

class Company{
-designation
}
@enduml