@startuml
'https://plantuml.com/sequence-diagram
hide methods
skinparam classAttributeIconSize 0


Company"1" -- "*"Admin :> employs
Company"1" -- "*"TypeOfTest:> conducts
Company"1" -- "*"Category :> adopts
Admin"1" -- "*"TypeOfTest :< created by
TypeOfTest"*" -- "1"Category :> has a
Admin"1" -- "*"Category :< created by

class TypeOfTest{
-code
-description
-collecting method
}

class Admin{
  -name
  -function
  -phone
  -email
}

class Company{
-designation
}

class Category{
    -code
    -name
}
@enduml