@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0

class Company {
 -designation
}

class ClinicalAnalysisTest {
  - nhsCode
  - client
  - typeOfTest
  - parameterList
  - labWhereCreated
 }

class TypeOfTest {
  -code
  -description
  -collectingMethod
}



class Client {
  - name
  - citizenCardNumber
  - nhsNumber
  - birthDate
  - sex
  - tin
  - phoneNumber
  - email
}

class Parameter {
-name
-code
-description
}

class ParameterCategory {
-code
-name
}


Company "1" -- "*" ClinicalAnalysisTest : performs >
ClinicalAnalysisTest "*" -- "1" TypeOfTest: is of >
ClinicalAnalysisTest "1..*" -- "1" Client: requested by >
Parameter "1..*" -- "1" ParameterCategory: presented under >
Parameter "1..*" --> "1" ClinicalAnalysisTest : has >
TypeOfTest "1" --> "1..*" ParameterCategory :  has
Company "1" --> "1..*" Client : knows

@enduml