@startuml
autonumber

actor "Specialist Doctor" as SD

participant ":System" as SYSTEM

SD -> SYSTEM : Write a report for a test
activate SYSTEM
loop while the user wants to write another report\n or there are still tests ready to receive a report
SYSTEM --> SD : Asks for which existing test he wants to write a report for
deactivate SYSTEM

SD -> SYSTEM : Selects the test
activate SYSTEM
SYSTEM --> SD : Shows test results available
deactivate SYSTEM

SD -> SYSTEM : Writes the report
activate SYSTEM
SYSTEM --> SD : Validates the report and asks for confirmation
deactivate SYSTEM

SD -> SYSTEM : Confirms the report
activate SYSTEM
SYSTEM --> SD : Informs that the report was saved successfully
deactivate SYSTEM
end loop
@enduml