@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Administrator" as Ad
participant ":SendReportUI" as UI
participant ":SendReportController" as CTRL
participant "comp\n:Company" as COMP




participant "testStore: TestStore" as TSTORE

participant "RegressionModel" as SAMPLE
participant "testMap:TestMapper" as TMAPPER
participant "NHS" as  N

activate Ad

Ad-> UI : start the report
activate "UI"
"UI"--> Ad : Ask for to select the time measure(days or weeks)
deactivate "UI"
Ad -> "UI" : select measure
activate "UI"



@enduml