@startuml
'https://plantuml.com/use-case-diagram
hide methods
skinparam classAttributeIconSize 0

class Company{
-designation
}

class Client {
-name
-citizenCardNumber
-nhsNumber
-tinNumber
-birthDate
-sex
-phoneNumber
-email
}

class ClinicalAnalysisTest {
- nhsCode
- client
- typeOfTest
- parameterList
- labWhereCreated
}

class Report {
- createdAt
- reportText
}
Company"1" -- "*"Client :> knows
Client"1" -- "1..*" Report :> access
Company "1" -- "*" ClinicalAnalysisTest :> owns
Client "1" -- "1..*" ClinicalAnalysisTest :> belongs
@enduml

