@startuml
autonumber
'hide footbox
actor "Client" as CLIENT

participant ":System" as SYSTEM

CLIENT -> SYSTEM : Log in the client account
activate SYSTEM

SYSTEM --> CLIENT : Authentication Response
deactivate SYSTEM

CLIENT -> SYSTEM : See the list of tests who have performed ordered by the registration date
activate SYSTEM
SYSTEM --> CLIENT : Shows the validated test list who have performed ordered by the registration date
deactivate SYSTEM
loop
CLIENT -> SYSTEM : Choose the test you want to see and your respective results
activate SYSTEM
SYSTEM --> CLIENT : Shows the result of the chosen test
deactivate SYSTEM
CLIENT -> SYSTEM : Confirms all data
activate SYSTEM
SYSTEM --> CLIENT : Informs operation success
deactivate SYSTEM
end

@enduml