@startuml
autonumber
'hide footbox
actor "Client" as CLIENT

participant ":ViewTestResultUI" as UI
participant ":ViewTestResultController" as CTRL
participant ":Company" as COMP
participant "store:ClientStore" as STR
participant "store:TestStore" as TTS
participant ":ClinicalTest" as T
participant ":Report" as R
participant ":Email" as EM
participant ":UserSession" as US
participant ":AuthFacade" as AF


CLIENT -> UI: Log in the client account
activate UI

UI -> CTRL: getClientByEmail()
activate CTRL
deactivate UI

CTRL-> COMP : store=getClientStore()
activate COMP
deactivate COMP
CTRL->STR : client = getClientByEmail()
activate STR
STR-> AF :emailUser=getCurrentSession()
activate AF
deactivate AF
STR -> US : id = getUserId()
activate US
deactivate US
deactivate CTRL



STR->EM: email = getEmail()
activate EM
deactivate EM
deactivate STR
deactivate STR

UI --> CLIENT: Authentication Response
activate UI
deactivate UI



CLIENT -> UI: See the list of  validated tests who have performed ordered by the registration date
activate UI
deactivate UI




UI -> CTRL: showClientTestsValidatedAndOrderedByRegistrationDate()
activate UI
deactivate UI
activate CTRL
deactivate CTRL

CTRL -> COMP: store=getTestStore()
activate CTRL
deactivate CTRL
activate COMP
deactivate COMP

CTRL -> TTS: getClientTestsValidatedAndOrderedByRegistrationDate()
activate CTRL
deactivate CTRL
activate TTS
deactivate TTS


UI --> CLIENT: Shows the validated test list who have performed ordered by the registration date

loop
CLIENT -> UI: Choose the test you want to see and your respective results and report
activate UI
deactivate UI

UI -> CTRL: showTestSelected(nhsCode)
activate UI
deactivate UI
activate CTRL
deactivate CTRL

CTRL -> TTS: getTestByNhsCode(nhsCode)
activate CTRL
deactivate CTRL
activate TTS
deactivate TTS

UI -> CTRL: showTestResultsAndReport()
activate UI
deactivate UI
activate CTRL
deactivate CTRL

CTRL -> T: getTestResults()
activate CTRL
deactivate CTRL
activate T
deactivate T


CTRL -> T: getReportText()
activate CTRL
deactivate CTRL
activate T
deactivate T

T -> R: getReportText()
activate T
deactivate T
activate R
deactivate R



UI --> CLIENT: Shows the result of the chosen test and your report
activate UI
deactivate UI

CLIENT -> UI: Confirms all data
activate UI
deactivate UI



UI --> CLIENT: Informs operation success
end

@enduml