@startuml

autonumber

participant "store: \n Client Store" as CS
participant ": \n SendingEmail" as SE
participant "client: \n Client" as C

activate CS
CS -> CS : sendEmail(client, pwd
activate CS
CS -> C : name=getName()
activate C
deactivate C
CS -> C : email=getEmail()
activate C
deactivate C
CS -> SE : sendEmailWithPassword(name, email, pwd)
activate SE
deactivate SE

@enduml