@startuml
'https://plantuml.com/sequence-diagram

Company -- Receptionist :> has
Company -- Client :> stores
Receptionist -- Client :> add new

class Client{
-name
-citizenCardNumber
-nhsNumber
-tinNumber
-birthDate
-sex
-phoneNumber
-email
}

class Company{
-designation
}
@enduml