@startuml

hide methods


class Company{
 -designation
}

class Client{
 -name
 -tinNumber
 -citizenCardNumber
 -nhsNumber
 -birthDate
 -sex
 -phoneNumber
 -email
}

class Employee{
 -employeeID
 -name
 -address
 -socCode
 -phoneNumber
 -email
}

class Report{
 -diagnosis
}

class Result{
 -parameter
}

class Parameter{
 -name
 -code
 -description
}

class ParameterCategory{
 -code
 -name
}

class TypeOfTest{
 -description
 -code
 -collectingMethods
}

class Laboratory{
 -name
 -phoneNumber
 -tinNumber
 -address
}

class ClinicalAnalysisLaboratory {
 -laboratoryId
}

class SpecialistDoctor {
 -doctorIndexNumber
}

class Sample {
 -barcodeNumber
}

class Test {
 -testRegistrationDate
 -chemicalAnalysisDate
 -diagnosisDate
}

class ChemicalLab {
}

class User {
 -email
 -name
 -password
}

class OrganizationRole {
 -description
}

Company"1" -up- "*"Client : "> knows"
Company"1" -left- "*"Employee : "> employs"
Company"1" -- "1"ChemicalLab : "> owns"
Employee <|-- SpecialistDoctor
ChemicalLab --|> Laboratory
ClinicalAnalysisLaboratory -|> Laboratory
Employee"0..1" -- "1"User : "> registered as"
TypeOfTest"*" -right- "1..*"ParameterCategory : "> can measure \n parameters under a"
Parameter"*" -- "1"ParameterCategory : "> categorized under a"
Employee"*" -up- "1"OrganizationRole : "> has an"
Company"1" -- "*"ClinicalAnalysisLaboratory : "> owns"
ClinicalAnalysisLaboratory"*" -- "1..*"TypeOfTest : "> performs"
Company"1" - "*"TypeOfTest : "> conducts"
Sample"1" -- "1"Result : "> receives"
Result"1" - "1"Report : "> originates"
Report"*" -- "*"Client : "> sent to"
Client"0..1" -up- "1"User : "> becomes"
Employee <|-- Admin
Admin"1..*" -- "*"ParameterCategory : "> specifies"
Company"1" -- "*"ParameterCategory : "> adopts"
Admin"1..*" -- "*"TypeOfTest : "> specifies"
Admin"1..*" -- "*"Parameter : "> specifies"

Employee <|- Receptionist
Receptionist"1..*" -- "*"Test : "> register"
Receptionist"1..*" -- "*"Client : "> register"

Test"*" -- "*"Sample : "> has"

Client"*" -left- "1..*"Test : "> asks for"

Employee <|-left- MedicalLabTechnician
MedicalLabTechnician"1..*" -- "*"Sample : "> register"

Employee <|-- ClinicalChemistryTechnologist
ClinicalChemistryTechnologist"1..*" -- "*"Result : "> record"

SpecialistDoctor"1..*" -- "*"Report : "> write"
Company"1" -- "*"Parameter : "> capable of analysing"
Employee <|- LaboratoryCoordinator
LaboratoryCoordinator"1..*" -- "*"Report : "> validates"
LaboratoryCoordinator"1..*" -- "*"Result : "> validates"

@enduml